import { Role } from "src/modules/user/enums/role.enum";

export const gardenersMock = [
    {
        name: "Juan Perez",
        email: "jardinero@gmail.com",
        username: "GardnerJuan",
        password: "password123",
        confirmPassword: "password123",
        phone: "5551234",
        address: "Avenida Jardín 45",
        age: 30,
        role: Role.Gardener,
        experience: "Experto en diseño y mantenimiento de jardines.",
        calification: 4,
        ubication: "Av. Siempre Viva 742",
        costPerHour: 2000,
        profileImageUrl: "gardener/i21jki2m58j7rrgh12rt",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Ana Lopez",
        email: "ana.lopez@gmail.com",
        username: "GardnerAna",
        password: "password456",
        confirmPassword: "password456",
        phone: "5555678",
        address: "Calle Verde 102",
        age: 28,
        role: Role.Gardener,
        experience: "Especialista en poda y cuidado de césped.",
        calification: 3,
        ubication: "Los Robles 67",
        costPerHour: 1800,
        profileImageUrl: "gardener/vja4j61zfcdl8qk1iccv",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Carlos Ramirez",
        email: "carlos.ramirez@gmail.com",
        username: "GardnerCarlos",
        password: "password789",
        confirmPassword: "password789",
        phone: "5554321",
        address: "Camino del Árbol 58",
        age: 35,
        role: Role.Gardener,
        experience: "Amplia experiencia en instalación de sistemas de riego y cuidado de plantas.",
        calification: 5,
        ubication: "Jardines del Valle 112",
        costPerHour: 2200,
        profileImageUrl: "gardener/gnfmj6z3a7c0oncgr05i",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Maria Torres",
        email: "maria.torres@gmail.com",
        username: "GardnerMaria",
        password: "password101",
        confirmPassword: "password101",
        phone: "5558765",
        address: "Ruta Floral 17",
        age: 40,
        role: Role.Gardener,
        experience: "Profesional en diseño de jardines y paisajismo.",
        calification: 2,
        ubication: "Las Margaritas 23",
        costPerHour: 2500,
        profileImageUrl: "gardener/flkyg5ey9eamunc6fnid",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Lucas Díaz",
        email: "lucas.diaz@gmail.com",
        username: "GardnerLucas",
        password: "password202",
        confirmPassword: "password202",
        phone: "5559876",
        address: "Verde Olivo 92",
        age: 26,
        role: Role.Gardener,
        experience: "Hábil jardinero con experiencia en mantenimiento de jardines.",
        calification: 1,
        ubication: "Pinos de la Colina 34",
        costPerHour: 1900,
        profileImageUrl: "gardener/Perfil7.jpg",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Sofía Martínez",
        email: "sofia.martinez@gmail.com",
        username: "GardnerSofia",
        password: "password303",
        confirmPassword: "password303",
        phone: "5551122",
        address: "Campo Verde 33",
        age: 32,
        role: Role.Gardener,
        experience: "Diseño innovador de jardines verticales.",
        calification: 4,
        ubication: "Colonia Verde 23",
        costPerHour: 2300,
        profileImageUrl: "gardener/image_sg3pohvke8",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Diego Sánchez",
        email: "diego.sanchez@gmail.com",
        username: "GardnerDiego",
        password: "password404",
        confirmPassword: "password404",
        phone: "5553344",
        address: "Plaza de los Árboles 77",
        age: 29,
        role: Role.Gardener,
        experience: "Especialista en decoración con plantas exóticas.",
        calification: 5,
        ubication: "Los Almendros 101",
        costPerHour: 2600,
        profileImageUrl: "gardener/img_ds7",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Andrea Fernández",
        email: "andrea.fernandez@gmail.com",
        username: "GardnerAndrea",
        password: "password505",
        confirmPassword: "password505",
        phone: "5555566",
        address: "Jardín de Flores 11",
        age: 31,
        role: Role.Gardener,
        experience: "Mantenimiento de áreas verdes y parques.",
        calification: 3,
        ubication: "Verde Manzana 45",
        costPerHour: 2100,
        profileImageUrl: "gardener/img_af.jpg",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Miguel Rodríguez",
        email: "miguel.rodriguez@gmail.com",
        username: "GardnerMiguel",
        password: "password606",
        confirmPassword: "password606",
        phone: "5557788",
        address: "Ruta Verde 19",
        age: 27,
        role: Role.Gardener,
        experience: "Jardinero urbano con experiencia en jardines pequeños.",
        calification: 4,
        ubication: "Esquina Flor 56",
        costPerHour: 1950,
        profileImageUrl: "gardener/mr_profil.jpg",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Elena Ruiz",
        email: "elena.ruiz@gmail.com",
        username: "GardnerElena",
        password: "password707",
        confirmPassword: "password707",
        phone: "5558899",
        address: "Verde Bosque 66",
        age: 34,
        role: Role.Gardener,
        experience: "Diseño sostenible de jardines ecoamigables.",
        calification: 5,
        ubication: "Bosque Azul 98",
        costPerHour: 2500,
        profileImageUrl: "gardener/er_img.jpg",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    },
    {
        name: "Luis Gómez",
        email: "luis.gomez@gmail.com",
        username: "GardnerLuis",
        password: "password808",
        confirmPassword: "password808",
        phone: "5559900",
        address: "Paseo Verde 74",
        age: 40,
        role: Role.Gardener,
        experience: "Jardinero experimentado en diseño de caminos con flores.",
        calification: 3,
        ubication: "Jardines Altos 23",
        costPerHour: 2200,
        profileImageUrl: "gardener/luis_gomez.jpg",
        serviceProvided: [],
        serviceDeails: [],
        carrouselImages: []
    }
];
