name: Notify Discord on Push

on:
  push:
    branches:
      - Develop # Cambia esta línea si quieres monitorear otra rama
      - Back
      - Front-v2

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          branch_name=${GITHUB_REF##*/}
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Nuevo commit en el repositorio: **${{ github.repository }}**\nAutor: **${{ github.event.head_commit.author.name }}**\nMensaje: **${{ github.event.head_commit.message }}**\nRama: **$branch_name**\nEnlace: [Ver Commit](${{ github.event.head_commit.url }})\"}" \
          $DISCORD_WEBHOOK_URL
