name: Notify Discord on Push and Merge

on:
  push:
    branches:
      - Develop 
  pull_request:
    types:
      - closed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            branch_name=${GITHUB_REF##*/}
            curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"Nuevo commit en el repositorio: **${{ github.repository }}**\nAutor: **${{ github.event.head_commit.author.name }}**\nMensaje: **${{ github.event.head_commit.message }}**\nRama: **$branch_name**\nEnlace: [Ver Commit](${{ github.event.head_commit.url }})\"}" \
            $DISCORD_WEBHOOK_URL
          elif [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.merged }}" = "true" ]; then
            branch_name=${{ github.event.pull_request.base.ref }}
            curl -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"Se ha mergeado una Pull Request en el repositorio: **${{ github.repository }}**\nAutor: **${{ github.event.pull_request.user.login }}**\nTítulo: **${{ github.event.pull_request.title }}**\nRama destino: **$branch_name**\nEnlace: [Ver Pull Request](${{ github.event.pull_request.html_url }})\"}" \
            $DISCORD_WEBHOOK_URL
          fi
